# General GitHub Repository Settings
repository:
  license: MIT      # Select a license from the options below

# MATLAB Toolbox Settings
matlab_toolbox:
  namespace_name: AIDIF                         # A unique namespace for your toolbox
  toolbox_name: AIDIF Matlab Toolbox            # Name of the MATLAB toolbox                  
  author_name: Lane Desborough                     
  author_email: lane@aidif.org         
  author_company: aidif.org                     # Author's company or organization
  toolbox_summary: A comprehensive set of validated models and tools to perform pre-clinical evaluation for AID systems and their components. 
  toolbox_description: |
    The AID Interoperability Framework (AIDIF) is intended to be a public, modular computational modeling and simulation environment for development and evaluation of AID systems and components. Building on over a decade of proprietary simulator development experience, AIDIF aims to integrate validated models of CGMs, insulin pumps, and control algorithms with physiological and behavioral models derived from public high quality and representative clinical data. 
  dependencies:                                     # Required MATLAB products
    - MATLAB
    - Matlab Simulink

# Publishing options
codecov:
  badge_token: null

fileexchange:
  fex_url: null
